
export const postData = [
  {
    imgPost: "/dummy1.jpg",
    likes: "49",
    comments: "85",
    desc: "A beautiful hill side village",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },

  {
   dummy:true,videoUrl: "/32PouIfy02Y",
    likes: "294",
    comments: "33",
    desc: "preview of netflix-project",
    username: "Rakesh Mandal",
    createdAt: "20-4-2023",
  },
  {
    imgPost: "/resume-builder.png",
    likes: "294",
    comments: "33",
    desc: "create resume with AI in few minutes",
    username: "Rakesh_Mandal",
    createdAt: "20-4-2023",
  },

  {
   dummy:true,videoUrl: "/WmVVWf6oBF8",
    likes: "203",
    comments: "45",
    desc: "my own youtube application",
    username: "Rakesh_Mandal",
    createdAt: "30-3-2023",
  },
  {
    imgPost: "/dummy2.jpg",
    likes: "203",
    comments: "45",
    desc: "A red leaf path of peace",
    username: "Rakesh_Mandal",
    createdAt: "30-3-2023",
  },

  {
    imgPost: "/dummy3.jpg",
    likes: "195",
    comments: "20",
    desc: "simple tic-tac-toe game",
    username: "Rakesh_Mandal",
    createdAt: "10-12-2022",
  },
  {
   dummy:true,videoUrl: "/Pk_qBTqTLs0",
    likes: "195",
    comments: "20",
    desc: "simple calculater for arithmetic calculations",
    username: "Rakesh_Mandal",
    createdAt: "10-12-2022",
  },

  {
   dummy:true,videoUrl: "/_u-4XLLgZ7M",
    likes: "599",
    comments: "132",
    desc: "frontend counterpart for an e-commerce website",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
  {
    imgPost: "/dummy4.jpg",
    likes: "599",
    comments: "132",
    desc: "Tracking is the most lovable tough thing as adventure",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
  {
   dummy:true,videoUrl: "/XpoiGVBWQ08",
    likes: "599",
    comments: "132",
    desc: "counter timer",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
  ,
  {
   dummy:true,videoUrl: "/hK6Z-ooqqVc",
    likes: "599",
    comments: "132",
    desc: "Tic-tac toe game built with html,css and js",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
  ,
  {
   dummy:true,videoUrl: "/wxT-Be9b-eo",
    likes: "599",
    comments: "132",
    desc: "Appointment Booking appplication for patients",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
  {
    imgPost: "/dummy5.jpg",
    likes: "599",
    comments: "132",
    desc: "Books are best partner for wisdom",
    username: "Rakesh Mandal",
    createdAt: "20-2-2023",
  },
];


